NTNB class in Brazilian government bonds structure
Finance-Hub/FinanceHub pull request #48
Opened 2021-04-03 01:07 UTC by lucaslsanches

Added NTNB class in Brazilian government bonds

2021-04-24 13:50 UTC, gusamarante requested changes

2021-04-24 13:50 UTC, gusamarante commented on finmath/brazilian_bonds/government_bonds.py
> +                 principal: float = 1e6,
Porque esse `principal` é necessário? o VNA da NTNB já é o principal dela

2021-04-24 13:50 UTC, gusamarante commented on finmath/brazilian_bonds/government_bonds.py
> +class NTNB(object):
Precisa incluir essa classe (e a dos outros bonds) no construtor da biblioteca `finmath`. É o arquivo `__init__.py` que fica dentro dela.

2021-04-24 13:52 UTC, gusamarante commented
Testei a classe com os dados do dia 23 de abril de 2021. O preço fica só com 0.12% de diferença para o que a ANBIMA publicou.

```python
from finmath.brazilian_bonds.government_bonds import NTNB

ntn = NTNB(expiry='2050-08-15',
           rate=0.044125,
           updated_nominal_value=3517.844181,
           ref_date='2021-04-23')

print('Preço calculado foi de', ntn.price)
print('PU na ANBIMA é de 4.460,278154')
```

2021-05-02 23:37 UTC, lucaslsanches commented
Oi Gustavo, boa noite, tudo bom?

Obrigado pelos feedbacks!
Olhando os outros pull requests, acho que o do Pedro está mais adiantado para fazer o merge.
Dado que ele também resolveu algumas convenções numéricas da Anbima, acho que seria um acréscimo melhor para o FinanceHub.
Podemos seguir com a solução dele, mesmo.

Muito obrigado!
Abraços!

2021-05-02 23:37 UTC, closed without merging